channels:
  - conda-forge
dependencies:
  - python={% if cookiecutter.python_interpreter == 'python3' %}3{% else %}2.7{% endif %}
  - pip
  - coverage
  - flake8
  - black
  - fire
  - jupyterlab
  - python-dotenv>=0.5.1
  - pip:
    - -r requirements.txt
